### PR TITLE
docs: updating example pr list with ui examples

### PR DESCRIPTION
**Pull request by georgewrmarshall**
## **Description**

This PR adds to the PR example list with UI-specific entries. These additions serve as comprehensive examples of well-documented UI PRs, featuring detailed descriptions, manual testing steps, and before-and-after screen recordings. This enhancement aims to set a robust standard for future UI-related PRs.

## **Related issues**

Fixes: #73
Closes: https://app.zenhub.com/workspaces/design-system-61e8a2ae77c3a60012e5003c/issues/zh/351

## **Manual testing steps**

1. Go to `docs/pull-requests.md`
2. Check added PR examples links
3. Ensure PRs are good example candidates 

### **Before**

https://github.com/MetaMask/contributor-docs/assets/8112138/b35d5bbb-4d26-4108-9e5d-8ceff0cfd714

### **After**

https://github.com/MetaMask/contributor-docs/assets/8112138/df8532f8-d919-47b8-aa9b-d704738349c9

### CODE REVIEW

**Comment by mcmire** [comment]
There isn't anything around providing screenshots/videos in the instructions here. Maybe that's something we should add? For instance, instead of:

> - **What is your solution?** How do your changes satisfy the need? Are there any changes in particular whose purpose might not be obvious or whose implementation might be difficult to decipher? How do they work?

Maybe:

> - **What is your solution?** How do your changes satisfy the need? Are there any changes in particular whose purpose might not be obvious or whose implementation might be difficult to decipher? How do they work? If you made UI changes, are there any screenshots or videos you can provide to illustrate the solution?

**Comment by georgewrmarshall** [comment]
> ef0f20e

Great suggestion! Updated here: https://github.com/MetaMask/contributor-docs/pull/75/commits/ef0f20efb0380f682c0474e7b07b0d28d5475073

**Comment by georgewrmarshall** [comment]
> There isn't anything around providing screenshots/videos in the instructions here. Maybe that's something we should add? For instance, instead of:
> 
> > * **What is your solution?** How do your changes satisfy the need? Are there any changes in particular whose purpose might not be obvious or whose implementation might be difficult to decipher? How do they work?
> 
> Maybe:
> 
> > * **What is your solution?** How do your changes satisfy the need? Are there any changes in particular whose purpose might not be obvious or whose implementation might be difficult to decipher? How do they work? If you made UI changes, are there any screenshots or videos you can provide to illustrate the solution?

Great suggestion! Updated here: https://github.com/MetaMask/contributor-docs/pull/75/commits/ef0f20efb0380f682c0474e7b07b0d28d5475073

**Review by mcmire — APPROVED** [review]
Looks good!

**Pull request merged**
